export const CLOTHING_STORE_DATA_LOADED =
  "CLOTHING_STORE_DATA/CLOTHING_STORE_DATA_LOADED";
export const TOGGLE_CURRENCY = "CLOTHING_STORE_DATA/TOGGLE_CURRENCY";
export const ADD_PRODUCT_TO_CART = "CLOTHING_STORE_DATA/ADD_PRODUCT_TO_CART";
export const CHANGE_PRODUCT_QUANTITY =
  "CLOTHING_STORE_DATA/CHANGE_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT = "CLOTHING_STORE_DATA/REMOVE_PRODUCT";
