export const TOGGLE_CURRENCY = "CLOTHING_STORE_DATA/TOGGLE_CURRENCY";
export const ADD_PRODUCT_TO_CART = "CLOTHING_STORE_DATA/ADD_PRODUCT_TO_CART";
export const CHANGE_PRODUCT_QUANTITY =
  "CLOTHING_STORE_DATA/CHANGE_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT = "CLOTHING_STORE_DATA/REMOVE_PRODUCT";
export const CATEGORY_NAMES_AND_CURRENCIES_LOADED =
  "CLOTHING_STORE_DATA/CATEGORY_NAMES_AND_CURRENCIES_LOADED";
export const CATEGORY_LOADED = "CLOTHING_STORE_DATA/CATEGORY_LOADED";
// export const CURRENCIES_LOADED = "CLOTHING_STORE_DATA/CURRENCIES_LOADED";
export const PRODUCT_LOADED = "CLOTHING_STORE_DATA/PRODUCT_LOADED";
export const PRODUCT_BEGIN_LOADING =
  "CLOTHING_STORE_DATA/PRODUCT_BEGIN_LOADING";
